# Generated by Django 6.1 on 2026-08-09 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0002_exerciselog_setlog_workoutsession_workoutfeedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(blank=True, max_length=150)),
                ('decision', models.CharField(choices=[('increase_load', 'Increase Load'), ('decrease_load', 'Decrease Load'), ('decrease_volume', 'Decrease Volume'), ('maintain', 'Maintain')], max_length=32)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_history', to=settings.AUTH_USER_MODEL)),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_decisions', to='workouts.workoutsession')),
            ],
            options={
                'verbose_name_plural': 'adaptation history',
                'ordering': ['-created_at'],
            },
        ),
    ]
