# Generated by Django 6.1 on 2026-08-09 13:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('build_muscle', 'Build Muscle'), ('lose_fat', 'Lose Fat'), ('increase_strength', 'Increase Strength'), ('improve_fitness', 'Improve Fitness'), ('build_habits', 'Build Healthy Habits')], max_length=32)),
                ('motivation', models.CharField(choices=[('looking_better', 'Looking Better'), ('lifting_heavier', 'Lifting Heavier'), ('consistency', 'Consistency'), ('health', 'Health'), ('athletic_performance', 'Athletic Performance')], max_length=32)),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=32)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=16)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('training_environment', models.CharField(choices=[('commercial_gym', 'Commercial Gym'), ('home_gym', 'Home Gym'), ('limited_equipment', 'Limited Equipment')], max_length=32)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('training_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('workout_duration', models.CharField(choices=[('30', '30 min'), ('45', '45 min'), ('60', '60 min'), ('90+', '90+ min')], max_length=8)),
                ('training_style', models.CharField(choices=[('high_intensity', 'High Intensity'), ('progressive_overload', 'Progressive Overload'), ('high_volume', 'High Volume'), ('balanced', 'Balanced')], max_length=32)),
                ('priority_muscles', models.JSONField(blank=True, default=list)),
                ('injuries', models.TextField(blank=True)),
                ('coach_personality', models.CharField(choices=[('direct', 'Direct'), ('supportive', 'Supportive'), ('balanced', 'Balanced'), ('adaptive', 'Adaptive')], max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
