# Generated by Django 6.1 on 2026-08-10 18:35

import django.core.validators
from django.db import migrations, models


def normalize_workout_duration(apps, schema_editor):
    """The old field allowed the literal '90+' choice, which can't cast to an
    integer column. Map it to a concrete number before the type change."""
    OnboardingProfile = apps.get_model('onboarding', 'OnboardingProfile')
    OnboardingProfile.objects.filter(workout_duration='90+').update(workout_duration='90')


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingprofile',
            name='training_style',
        ),
        migrations.RunPython(normalize_workout_duration, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='onboardingprofile',
            name='workout_duration',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
