# Generated by Django 6.1 on 2026-08-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exerciselog_setlog_workoutsession_workoutfeedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('muscle_group', models.CharField(max_length=50)),
                ('equipment_needed', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['muscle_group', 'name'],
            },
        ),
        migrations.AddField(
            model_name='plannedexercise',
            name='target_rir',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setlog',
            name='is_warmup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setlog',
            name='rir',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plannedexercise',
            name='rest_seconds',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
